### ISSUE TITLE
论文中的两个小疑问

### ISSUE THREAD

**Issue by HaimianYu** [lancopku/SGM#14]
您好，我对您论文中有两个小疑问，因为不知道怎么打公式，我把问题放在了图片中，希望您能解答，谢谢
![ko2 a46lc0tmt eu39 gttn](https://user-images.githubusercontent.com/42952354/50438583-83bcac00-0929-11e9-81cd-9d6f3d70821e.png)

**Comment by ypengc7512** [comment]
Later in the experiment we found that this attention performs better. Attention represents a basic idea, and there are many ways for implementation. This does not affect the overall architecture of the model.
