### ISSUE TITLE
预测为 label 序列，例如 MCAT ECAT M13 M131 E12

### ISSUE THREAD

**Issue by Decalogue** [lancopku/SGM#4]
您好！
    请问预测的部分如何能预测为序列呢？而不是直接计算分数。
    例如 MCAT ECAT M13 M131 E12
    代码没太看懂。
多谢了！

**Comment by Decalogue** [comment]
请问是在 log 里面的 candidate 文件夹中的所有文件吗？例如candidate/candidate0 这样吗？
文件总数和测试集数据量是一样的，这个没问题。假设我的所有 tgt 序列长度都为n，打开每个文件后发现里面的长度并不是n，请问这是为什么呢？

**Comment by ypengc7512** [comment]
The label in the candidate is the label that the model predicted, so the number may not be $n$.

**Comment by Decalogue** [comment]
非常感谢！
问题找到了，是我的 label 重复了。后来把 label 的表示修改后就可以跑了。Macro-F1 和您论文中的一致。
非常想邀请您组队参加 AI challenger 2018 比赛——细粒度情感分析（https://challenger.ai/competition/fsauor2018），感觉您的 SGM 很适合这个题目。
这个比赛是对评论数据集的20个粒度每个粒度给出 [-2,-1,0,1] 的 label，其中-2表示未提及，-1是负面，0是中性，1是正面。根据计算每个粒度的 F1 ，然后20个粒度的 F1 求平均值得到最终分数，和您的评价标准有些区别。您可以看看数据集介绍，确实很适合您的模型。
我在拿到比赛数据时大致想法和您一样，没想到您已经发顶会论文了，大牛。我使用 seq2seq 做的，目前排在 20/160 左右。
希望可以组队。或者您看看数据集介绍对我们给点建议也是非常好的！

很认真的看完了您的论文，非常赞！

希望可以加个微信：yingluoqingli
QQ: 1044908508

**Comment by Decalogue** [comment]
请问预测的序列可以是定长的吗？谢谢！

**Comment by ypengc7512** [comment]
Yeah, the model can automatically determine the number of predicted labels by predicting $eos$.
