### ISSUE TITLE
What is the format of label_test?

### ISSUE THREAD

**Issue by linxid** [lancopku/SGM#5]
Is it meaning that data have different label length.
If my dataset's label is:

|id1|-2 | -2 | -2 | -2 | 1 | -2 | -2 | -2 | -2 | 1 | -2 | -2 | -2 | -2 | -2 | -2 | 1 | -2 | 1 | -2
-- |-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
|id2|-2 | -2 | -2 | -2 | -2 | -2 | -2 | 0 | -2 | 1 | 0 | 0 | 0 | 0 | 1 | -2 | -2 | -2 | 1 | -2

I only need to let label train is:
`-2 -2 -2 -2 1 -2 -2 -2 -2 1 -2 -2 -2 -2 -2 -2 1 -2 1 -2`
Thx

**Comment by ypengc7512** [comment]
The label sequences can have different lengths. The model can automatically determine the number of predicted labels by predicting $eos$.
