### ISSUE TITLE
i cant open the Google,can not get the dataset

### ISSUE THREAD

**Issue by hanyegirl** [lancopku/SGM#8]
我打不开谷歌，尝试了很多办法，更改hosts文件，使用谷歌镜像网站都试过了，仍没有办法打开，请问有别的链接可以下载数据集吗，万分感谢，或者发给我一份也好，我的qq:945900130。期待您的帮助

**Comment by ypengc7512** [comment]
I just uploaded the data to the Baidu cloud disk, you can download it through the link： https://pan.baidu.com/s/1Hgk9HdMppVCU7suUa_1usw

**Comment by hanyegirl** [comment]
谢谢你哦，杨老师，不过我看介绍代码多是使用的RCV1-2数据集，能不能给我一下这个数据集呢，万分感谢

**Comment by ypengc7512** [comment]
The RCV1-V2 data set is already in the compressed folder.

**Comment by hanyegirl** [comment]
谢谢，我看到了压缩文件是有data1,data2,data3,data4，请问一下RCV1-2是哪个文件呀

**Comment by ypengc7512** [comment]
The new download link is https://pan.baidu.com/s/14YPx9iKcw3hBkx6T97LNwg

**Comment by ypengc7512** [comment]
Sorry that I uploaded the wrong data set before.

**Comment by hanyegirl** [comment]
哈哈，谢谢哦，我要是有不会的地方能跟您请教吗
